import asyncio, json, struct, zlib
from playwright.async_api import async_playwright
import pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent/'public'/'index.html'
F=ROOT.as_uri()
res=[]
def ok(n,c,i=''): res.append(('✅' if c else '❌',n,str(i)[:160]))
async def ev(pg,js): return await pg.evaluate(js)
async def toast(pg):
    try: return await pg.inner_text('.toast',timeout=3000)
    except: return ''
async def login(pg,l,p):
    await pg.fill('#li_login',l); await pg.fill('#li_pw',p); await pg.click('#li_btn'); await pg.wait_for_timeout(700)
async def main():
  async with async_playwright() as P:
    b=await P.chromium.launch(); errs=[]
    ctx=await b.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True)
    await ctx.grant_permissions(['clipboard-read','clipboard-write'])
    pg=await ctx.new_page(); pg.on('pageerror',lambda e:errs.append(str(e)))
    await pg.goto(F); await ev(pg,'localStorage.clear()'); await pg.reload(); await pg.wait_for_timeout(1800)
    # ---- 1. Birinchi sozlash ----
    ok('Birinchi ochilishda admin yaratish ekrani', await pg.locator('text=Birinchi sozlash').count()==1)
    ok('Kodda default parol yo‘q', 'admin123' not in ROOT.read_text(encoding='utf-8'))
    await pg.fill('#su_name','Abdulloh'); await pg.fill('#su_login','admin'); await pg.fill('#su_pw','qisqa'); await pg.fill('#su_pw2','qisqa'); await pg.click('#su_btn')
    ok('Zaif parol rad etildi', '8' in await pg.inner_text('#su_err'), await pg.inner_text('#su_err'))
    await pg.fill('#su_pw','Dokon2026x'); await pg.fill('#su_pw2','Dokon2026y'); await pg.click('#su_btn')
    ok('Mos kelmagan parollar rad etildi','mos emas' in await pg.inner_text('#su_err'))
    await pg.fill('#su_pw2','Dokon2026x'); await pg.check('#su_demo'); await pg.click('#su_btn'); await pg.wait_for_timeout(1200)
    u=await ev(pg,'S.users[0]')
    ok('Admin yaratildi, parol ochiq saqlanmagan', u['login']=='admin' and 'Dokon2026x' not in json.dumps(u) and len(u['hash'])>30 and len(u['salt'])>10)
    ok('localStorage’da ochiq parol yo‘q','Dokon2026x' not in await ev(pg,"localStorage.getItem('telefon_dokon_v2')"))
    ok('Admin tizimga kirdi', await pg.locator('nav.bn').count()==1)
    # ---- 2. Chiqish va login ----
    await ev(pg,'logout()'); await pg.wait_for_timeout(200)
    await login(pg,'admin','NotoGri123')
    ok('Noto‘g‘ri parol rad etildi','noto‘g‘ri' in await pg.inner_text('#li_err'), await pg.inner_text('#li_err'))
    await login(pg,'yoqlogin','NotoGri123')
    e=await pg.inner_text('#li_err'); ok('Mavjud bo‘lmagan login uchun ham bir xil xabar','Login yoki parol noto‘g‘ri' in e,e)
    for _ in range(4): await login(pg,'admin','NotoGri123')
    e=await pg.inner_text('#li_err'); ok('5 xato urinishdan keyin blok','blok' in e.lower() or 'daqiqa' in e,e)
    await login(pg,'admin','Dokon2026x'); e=await pg.inner_text('#li_err')
    ok('Blok vaqtida to‘g‘ri parol ham kirmaydi','daqiqa' in e,e)
    await ev(pg,"S.lock.admin.until=Date.now()-1;save()")
    await login(pg,'admin','Dokon2026x')
    ok('Blok tugagach to‘g‘ri parol bilan kirish', await pg.locator('nav.bn').count()==1)
    # sessiya muddati
    await ev(pg,"SES.exp=Date.now()-1;localStorage.setItem(SKEY,JSON.stringify(SES));render()")
    ok('Sessiya muddati tugasa login so‘raladi', await pg.locator('#li_login').count()==1)
    await login(pg,'admin','Dokon2026x')
    # ---- 3. Xodim yaratish ----
    await ev(pg,'usersSheet()'); await pg.click('text=+ Yangi xodim')
    await pg.fill('#uf_n','Aziz'); await pg.fill('#uf_l','admin'); await pg.fill('#uf_pw','Sotuv2026a'); await pg.fill('#uf_pw2','Sotuv2026a'); await pg.click('#uf_btn'); await pg.wait_for_timeout(300)
    ok('Band login rad etildi','band' in await pg.inner_text('#uf_err'))
    await pg.fill('#uf_l','aziz'); await pg.uncheck('#uf_kirim'); await pg.click('#uf_btn'); await pg.wait_for_timeout(1200)
    ok('Sotuvchi yaratildi', await ev(pg,"S.users.some(u=>u.login==='aziz'&&u.role==='seller'&&!u.perms.kirim)"))
    # oxirgi adminni o‘chirib bo‘lmaydi / pasaytirib bo‘lmaydi
    aid=await ev(pg,"S.users.find(u=>u.login==='admin').id")
    r=await ev(pg,f"(()=>{{delUser({aid});return document.querySelector('.toast')?.textContent}})()")
    ok('Admin o‘zini o‘chira olmaydi','o‘zingiz' in (r or '').lower(),r)
    # ---- 4. Sotuvchi sifatida ----
    await ev(pg,'closeSheet();logout()'); await login(pg,'aziz','Sotuv2026a')
    ok('Sotuvchi kirdi', await ev(pg,"me().login")=='aziz')
    await ev(pg,"go('more')"); t=await pg.inner_text('#app')
    ok('Sotuvchida Xodimlar/Sozlamalar/Jurnal yo‘q','Xodimlar' not in t and 'Sozlamalar' not in t and 'jurnali' not in t)
    ok('Sotuvchida “+ Kirim” tugmasi yo‘q (ruxsat olib tashlangan)', await pg.locator('.fab').count()==0)
    r=await ev(pg,"(()=>{const n=S.users.length;usersSheet();return [n,document.querySelector('.toast')?.textContent]})()")
    ok('Sotuvchi Xodimlar oynasini chaqira olmaydi (funksiya darajasida)','ruxsat' in (r[1] or ''),r)
    r=await ev(pg,"(()=>{const n=S.units.length;kirimSheet();return document.querySelector('.toast')?.textContent})()")
    ok('Sotuvchi kirim funksiyasini chaqira olmaydi','ruxsat' in (r or ''),r)
    await ev(pg,"go('rep')"); t=await pg.inner_text('#app')
    ok('Sotuvchi tannarx/foydani ko‘rmaydi','Yalpi foyda' not in t and 'tannarx' not in t.lower())
    # profil: o‘z parolini o‘zgartirish
    await ev(pg,'profileSheet()'); await pg.fill('#pf_o','xato1234'); await pg.fill('#pf_n','Yangi2026b'); await pg.fill('#pf_n2','Yangi2026b'); await pg.click('#pf_btn'); await pg.wait_for_timeout(900)
    ok('Joriy parol xato bo‘lsa o‘zgarmaydi','noto‘g‘ri' in await pg.inner_text('#pf_err'))
    await pg.fill('#pf_o','Sotuv2026a'); await pg.click('#pf_btn'); await pg.wait_for_timeout(1500)
    ok('Sotuvchi o‘z parolini o‘zgartirdi va sessiyada qoldi', (await ev(pg,"me()?.login"))=='aziz')
    await ev(pg,'logout()'); await login(pg,'aziz','Sotuv2026a')
    ok('Eski parol endi ishlamaydi', await pg.locator('#li_err').count()==1 and 'noto‘g‘ri' in await pg.inner_text('#li_err'))
    await login(pg,'aziz','Yangi2026b'); ok('Yangi parol bilan kirdi', (await ev(pg,"me()?.login"))=='aziz')
    sess_aziz=await ev(pg,"localStorage.getItem(SKEY)")
    # ---- 5. Admin sotuvchi parolini yangilaydi -> sotuvchi sessiyasi tugaydi ----
    await ev(pg,'logout()'); await login(pg,'admin','Dokon2026x')
    zid=await ev(pg,"S.users.find(u=>u.login==='aziz').id")
    await ev(pg,f'userForm({zid})'); await pg.fill('#uf_pw','Reset2026c'); await pg.fill('#uf_pw2','Reset2026c'); await pg.check('#uf_cost'); await pg.click('#uf_btn'); await pg.wait_for_timeout(1300)
    await ev(pg,f"localStorage.setItem(SKEY,{json.dumps(sess_aziz)});SES=getSess();render()")
    ok('Parol yangilangach sotuvchining eski sessiyasi bekor', await pg.locator('#li_login').count()==1)
    await login(pg,'aziz','Reset2026c'); ok('Admin bergan yangi parol ishlaydi va tannarx huquqi qo‘shildi', await ev(pg,"me()?.login==='aziz'&&canCost()"))
    # o‘chirilgan hisob
    await ev(pg,'logout()'); await login(pg,'admin','Dokon2026x')
    await ev(pg,f'userForm({zid})'); await pg.uncheck('#uf_a'); await pg.click('#uf_btn'); await pg.wait_for_timeout(500)
    await ev(pg,'logout()'); await login(pg,'aziz','Reset2026c')
    ok('O‘chirilgan (nofaol) hisob kira olmaydi','o‘chirilgan' in await pg.inner_text('#li_err'))
    await login(pg,'admin','Dokon2026x')
    await ev(pg,f'userForm({zid})'); await pg.check('#uf_a'); await pg.click('#uf_btn'); await pg.wait_for_timeout(500); await ev(pg,'closeSheet()')
    # ---- 6. Mahsulot tahrirlash/o‘chirish ----
    await ev(pg,"kirimSheet()"); await pg.fill('#kb','Test'); await pg.fill('#km','Fon X'); await pg.fill('#kpr','2000000'); await pg.fill('#kcost','1500000')
    await pg.fill('#kimei','111111111111111\n222222222222222'); await pg.select_option('#ks','new'); await pg.fill('#ksn','Yangi Ta’minot'); await pg.fill('#kpaid','0'); await pg.click('text=Kirimni saqlash'); await pg.wait_for_timeout(300)
    pid=await ev(pg,"S.products.find(p=>p.model==='Fon X').id"); sid=await ev(pg,"S.suppliers.find(s=>s.name==='Yangi Ta’minot').id")
    ok('Kirim: 2 dona, ta’minotchi qarzi 3 mln', await ev(pg,f"supDebtOf({sid})")==3000000)
    await ev(pg,f'prodEdit({pid})'); await pg.fill('#pe_m','Fon X Pro'); await pg.fill('#pe_pr','2100000'); await pg.click('text=O‘zgarishlarni saqlash'); await pg.wait_for_timeout(200)
    ok('Mahsulot tahrirlandi', await ev(pg,f"gp({pid}).model==='Fon X Pro'&&gp({pid}).price===2100000"))
    ok('Kirim bo‘lgan mahsulotda kategoriya bloklangan', await ev(pg,f"(prodEdit({pid}),$('#pe_cat').disabled)"))
    await ev(pg,'closeSheet()')
    u1=await ev(pg,"S.units.find(u=>u.imei1==='111111111111111').id")
    await ev(pg,f'unitSheet({u1})'); await pg.fill('#ue_i1','222222222222222'); await pg.click('button.btn:text-is("Saqlash")'); await pg.wait_for_timeout(200)
    ok('IMEI tahririda takror rad etildi','bazada bor' in await toast(pg))
    await pg.fill('#ue_i1','333333333333333'); await pg.fill('#ue_base','1400000'); await pg.click('button.btn:text-is("Saqlash")'); await pg.wait_for_timeout(200)
    ok('IMEI va narx tahrirlandi, ta’minotchi qarzi 2.9 mln', await ev(pg,f"gu({u1}).imei1==='333333333333333'&&gu({u1}).cost===1400000&&supDebtOf({sid})===2900000"), await ev(pg,f"supDebtOf({sid})"))
    await pg.click('text=Kirim xatosi — o‘chirish'); await pg.click('#cyes'); await pg.wait_for_timeout(200)
    ok('Kirim xatosi o‘chirildi, qarz 1.5 mln', await ev(pg,f"!gu({u1})&&supDebtOf({sid})===1500000"), await ev(pg,f"supDebtOf({sid})"))
    ok('Tarixi bor ta’minotchini o‘chirib bo‘lmaydi', await ev(pg,f"(supEdit({sid}),!document.body.innerText.includes('Ta’minotchini o‘chirish'))"))
    # bo‘sh mahsulotni o‘chirish
    await ev(pg,"S.products.push({id:nid(),cat:'acc',brand:'Bosh',model:'Mahsulot',mem:'',color:'',cond:'new',price:1000,desc:'',img:null,min:0,archived:false});save()")
    epid=await ev(pg,"S.products.at(-1).id")
    await ev(pg,f'delProd({epid})'); await pg.click('#cyes'); ok('Tarixsiz mahsulot butunlay o‘chirildi', await ev(pg,f"!gp({epid})"))
    # ---- 7. Sotuv: qaytim, qarz muddati ----
    await ev(pg,"closeSheet();go('sale')")
    await ev(pg,"addUnitToCart(S.units.find(u=>u.imei1==='222222222222222').id)")
    await pg.fill('#pcash','2500000'); await pg.wait_for_timeout(200)
    t=await pg.inner_text('#ssum'); ok('Qaytim ko‘rsatildi: 400 000','400 000' in t and 'Qaytim' in t,t)
    await pg.click('#sbtn'); await pg.wait_for_timeout(900)
    s=await ev(pg,"(()=>{const s=S.sales.at(-1);return {paid:paidOf(s),due:dueOf(s),pay:S.payments.filter(p=>p.sale===s.id).map(p=>p.cash)}})()")
    ok('Qaytimli savdo: kassaga faqat 2.1 mln yozildi', s['paid']==2100000 and s['due']==0, s)
    await ev(pg,"closeSheet()")
    # nasiya + muddat
    await ev(pg,"addUnitToCart(S.units.find(u=>u.status==='stock'&&gp(u.pid).cat==='phone').id)")
    await pg.click('text=Nasiya (to‘lovsiz)'); await pg.select_option('select[aria-label=Mijoz]','new')
    await pg.locator('.g2 .fl input').nth(0).fill('Muddat Test'); await pg.locator('input[type=tel]').fill('+998 90 555 66 77')
    ok('Nasiyada muddat maydoni chiqdi', await pg.locator('#duew:not(.hide)').count()==1)
    await pg.click('#sbtn'); await pg.wait_for_timeout(900)
    dd=await ev(pg,"(()=>{const s=S.sales.at(-1);return Math.round((s.dueDate-Date.now())/864e5)})()")
    ok('Qarz muddati ~30 kun yozildi', 29<=dd<=31, dd)
    # ---- 8. Qarz to‘lovini bekor qilish ----
    sid2=await ev(pg,"S.sales.at(-1).id")
    await ev(pg,f"debtSheet({sid2})"); await pg.fill('#dc','1000000'); await pg.click('#dbtn'); await pg.wait_for_timeout(200)
    d1=await ev(pg,f"dueOf(gsale({sid2}))")
    await pg.locator('button:has-text("Bekor")').first.click(); await pg.click('#cyes'); await pg.wait_for_timeout(200)
    d2=await ev(pg,f"dueOf(gsale({sid2}))"); n=await ev(pg,f"S.payments.filter(p=>p.sale==={sid2}).length")
    ok('Qarz to‘lovi bekor: qarz qaytdi, asl yozuv saqlandi', d2-d1==1000000 and n==2, f'{d1}->{d2}, yozuvlar {n}')
    # ---- 9. Savdoni bekor qilish ----
    gp1=await ev(pg,"(()=>{const k=dkey(Date.now());return report(k,k).gp})()")
    await ev(pg,f"cancelSheet({sid2})"); await pg.click('text=Bekor qilishni tasdiqlash')
    ok('Sababsiz bekor qilinmaydi','Sabab' in await toast(pg))
    await pg.fill('#cr','Test xato'); await pg.click('text=Bekor qilishni tasdiqlash'); await pg.wait_for_timeout(200)
    c=await ev(pg,f"(()=>{{const s=gsale({sid2});const k=dkey(Date.now());return {{c:!!s.cancelled,st:gu(s.items[0].uid).status,due:dueOf(s),gp:report(k,k).gp}}}})()")
    ok('Savdo bekor: telefon omborga, qarz 0, foyda qaytarildi, tarix saqlandi', c['c'] and c['st']=='stock' and c['due']==0, c)
    # ---- 10. Xarajat tahrir/o‘chirish ----
    await ev(pg,"expSheet()"); await pg.fill('#ea','500000'); await pg.click('text=Xarajatni saqlash'); await pg.wait_for_timeout(200)
    eid=await ev(pg,"S.expenses.at(-1).id")
    await ev(pg,f"expEdit({eid})"); await pg.fill('#xa','450000'); await pg.click('button.btn:text-is("Saqlash")'); await pg.wait_for_timeout(200)
    ok('Xarajat tahrirlandi', await ev(pg,f"S.expenses.find(e=>e.id==={eid}).amount")==450000)
    await ev(pg,f"expEdit({eid})"); await pg.click('button.btn:text-is("O‘chirish")'); await pg.click('#cyes')
    k=dkey=None
    ok('Xarajat o‘chirildi va hisobotdan chiqdi, jurnalda iz bor', await ev(pg,f"S.expenses.find(e=>e.id==={eid}).del===true&&S.audit.some(a=>a.action==='Xarajat o‘chirildi')"))
    # ---- 11. Kassa ----
    kc=await ev(pg,"kassa().cash")
    await ev(pg,"kassaSheet()"); await pg.fill('#ka',str(kc-50000)); await pg.click('button:has-text("Kassani yopish")'); await pg.click('#cyes'); await pg.wait_for_timeout(200)
    ok('Kassa yopildi: kamomad −50 000 yozildi, yangi qoldiq = sanalgan', await ev(pg,f"S.closings.at(-1).diff===-50000&&kassa().cash==={kc-50000}"))
    # ---- 12. Mijoz tahrir/o‘chirish ----
    await ev(pg,"custSheet(0)"); await pg.fill('#cn','Vaqtinchalik'); await pg.fill('#cp','+998 93 000 00 01'); await pg.click('button.btn:text-is("Saqlash")'); await pg.wait_for_timeout(200)
    cid=await ev(pg,"S.customers.at(-1).id")
    await pg.fill('#cp','+998 97 123 45 67'); await pg.click('button.btn:text-is("Saqlash")'); ok('Takroriy telefon rad etildi','bor' in await toast(pg))
    await pg.click('text=Mijozni o‘chirish'); await pg.click('#cyes'); ok('Xaridsiz mijoz o‘chirildi', await ev(pg,f"!gc({cid})"))
    # ---- 13. Aksessuar hisobdan chiqarish ----
    bid=await ev(pg,"S.batches.find(b=>b.left>2).id")
    g0=await ev(pg,"(()=>{const k=dkey(Date.now());return report(k,k).wo})()")
    await ev(pg,f"batchSheet({bid})"); await pg.fill('#bw_q','2'); await pg.fill('#bw_r','Singan'); await pg.click('button:has-text("Hisobdan chiqarish")'); await pg.wait_for_timeout(200)
    g1=await ev(pg,"(()=>{const k=dkey(Date.now());return report(k,k).wo})()")
    ok('Hisobdan chiqarish zarar sifatida hisobotda', g1>g0, f'{g0}->{g1}')
    # ---- 14. Zaxira va tiklash ----
    await ev(pg,"closeSheet();exportData()"); await pg.wait_for_timeout(500)
    clip=await ev(pg,"navigator.clipboard.readText()")
    ok('Zaxira nusxa olindi, ochiq parol yo‘q', clip.startswith('{"app":"telefon-dokon"') and 'Dokon2026x' not in clip)
    nsales=await ev(pg,"S.sales.length")
    await ev(pg,"S.sales=[];save()")
    await ev(pg,"importSheet()"); await pg.fill('#imp',clip); await pg.click('button.btn.dg:has-text("Tiklash")'); await pg.click('#cyes'); await pg.wait_for_timeout(300)
    ok('Zaxiradan tiklandi va qayta login so‘raldi', await ev(pg,"S.sales.length")==nsales and await pg.locator('#li_login').count()==1)
    await login(pg,'admin','Dokon2026x')
    await ev(pg,"importSheet()"); await pg.fill('#imp','{"a":1}'); await pg.click('button.btn.dg:has-text("Tiklash")')
    ok('Begona fayl rad etildi','emas' in await toast(pg))
    await ev(pg,'closeSheet()')
    # ---- 15. XSS va magazin ----
    await ev(pg,"""S.customers.push({id:nid(),name:'<img src=x onerror="window.__x=1">',phone:'+998901112299',note:''});S.orders.push({id:nid(),date:Date.now(),name:'<svg onload="window.__x=1">',phone:'+998901112233',delivery:'olib ketish',address:'',comment:'<script>window.__x=1</script>',items:[{pid:S.products[0].id,qty:1}],status:'yangi'});save();ordersSheet()""")
    await pg.wait_for_timeout(200); await ev(pg,"custListSheet()"); await pg.wait_for_timeout(200)
    ok('XSS ishlamadi', await ev(pg,"window.__x||0")==0)
    await ev(pg,"closeSheet();openShop()"); txt=await pg.inner_text('#app')
    ok('Magazinda IMEI/tannarx yo‘q', not any(x in txt for x in ['356112233445501','11 800 000','Malika ulgurji']))
    ok('Magazin API (publicCatalog) maxfiy maydonsiz', await ev(pg,"Object.keys(publicCatalog()[0]).every(k=>!['cost','base','sup','imei1','note'].includes(k))"))
    # #magazin havolasi
    pg2=await ctx.new_page(); pg2.on('pageerror',lambda e:errs.append(str(e))); await pg2.goto(F+'#magazin'); await pg2.wait_for_timeout(1800)
    ok('#magazin havolasi faqat katalogni ochadi (orqaga tugmasi yo‘q)', await pg2.locator('button[aria-label=Orqaga]').count()==0 and await pg2.locator('.card').count()>0)
    await pg2.close()
    # ---- 16. Ekranlar ----
    await ev(pg,'closeShop()')
    for w in (360,390,430):
        await pg.set_viewport_size({'width':w,'height':740})
        bad=[]
        for t in ['home','prod','sale','rep','more']:
            await ev(pg,f"go('{t}')")
            if await ev(pg,'document.documentElement.scrollWidth')>w: bad.append(t)
        for sh in ['usersSheet()','settingsSheet()','kassaSheet()','custDebtSheet()','supSheet()',f'prodEdit({pid})','profileSheet()']:
            await ev(pg,sh)
            if await ev(pg,"document.querySelector('.sh').scrollWidth>document.querySelector('.sh').clientWidth"): bad.append(sh)
            await ev(pg,'closeSheet()')
        ok(f'{w}px: sahifa va modal oynalarda gorizontal scroll yo‘q', not bad, bad)
    ok('Splash ekran ochilishda chiqib, keyin yo‘qoladi', await pg.locator('#splash').count()==0)
    ok('JS xatolar yo‘q', not errs, errs[:3])
    await b.close()
asyncio.run(main())
f=sum(1 for r in res if r[0]=='❌')
for r in res: print(*r)
print(f'\nJAMI: {len(res)} test, {len(res)-f} o‘tdi, {f} xato')
